name: Version Validation

on:
  push:
    branches:
      - main

jobs:
  validation:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run Automation
        run: python automation.py

      - name: Upload validation report
        uses: actions/upload-artifact@v4
        with:
            name: validation_report
            path: validation_report.txt